# 12. Write a function to compute 5/0 and use try/except to catch 
# the exceptions

try:
    x=5/0
    print(x)
except:
    print("An exception occurred")